Hw js 4
ZhenyaSin/js pull request #3
Opened 2024-05-27 20:18 UTC by ZhenyaSin

Solving tasks "task1" and "task2"

2024-05-28 18:47 UTC, VladimirLQA requested changes

2024-05-28 18:47 UTC, VladimirLQA commented on HW_Lection4/Task1.js
> +let age_3 = 60;
Use `const`

2024-05-28 18:47 UTC, VladimirLQA commented on HW_Lection4/Task2_1.js
> +let age_3 = 61;
Use `const`

2024-05-28 18:47 UTC, VladimirLQA commented on HW_Lection4/Task2_2.js
> +let age_3 = 60;
Use `const`

2024-05-28 18:47 UTC, VladimirLQA commented on HW_Lection4/Task2_2.js
> +if (typeof age !== 'number' && !isNaN(age)) {
```suggestion
if (typeof age !== 'number') {
```

If follow task description we only need to check type of value

2024-05-28 18:47 UTC, VladimirLQA commented on HW_Lection4/Task2_3.js
> +if (typeof age === 'number') {
```suggestion
if (!isNaN(age)) {
```

Add output to `else` block for this case

2024-05-28 18:47 UTC, VladimirLQA commented on HW_Lection4/Task2_3.js
> +}
```suggestion
} else { ... }
```

2024-05-29 21:46 UTC, VladimirLQA approved these changes

2024-05-29 21:46 UTC, VladimirLQA commented on HW_Lection4/Task2_2.js
> +if (!isNaN(age)) {
This check need for 3-rd task

2024-05-29 21:46 UTC, VladimirLQA commented on HW_Lection4/Task2_3.js
> +if (typeof age === `number`) {
And this check for 2-nd :)

2024-05-30 21:06 UTC, anatoly-karpovich approved these changes

2024-05-31 09:27 UTC, VladimirLQA approved these changes

2024-06-08 10:46 UTC, merged